name: "Build"

on:
  push:
    branches:
      - main
      
jobs:
  build:
    name: Build and upload artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Build
        run: dotnet build -o .\outputs\test1.zip

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: Build ${{ github.run_number }}
          path: .\outputs\test1.zip
  Go-docs:
    name: Go Docs
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Documentation
      uses: nikeee/docfx-action@v1.0.0
      with:
        args: docfx_project/docfx.json
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
  publish-docs:
   name: Publish Docs
   needs: [Go-docs]
   runs-on: ubuntu-latest
   steps:
    - name: Chekout
      uses: actions/checkout@v3
      
    - name: Dotnet Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - run: dotnet tool update -g docfx
    - run: docfx docfx_project/docfx.json

    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: Build ${{ github.run_number }} 
        path: ./_site
